### ISSUE TITLE
Tail files for log streaming

### ISSUE THREAD

**Issue by brandonros** [valeriansaliou/node-sonic-channel#1]
I'd imagine it's pretty normal that most apps write logs to files while they are running.

It's not clear (to me at least) whether I need to write my own code to stream the logs to the sonic-server using a library like this, or if sonic-server can watch a pattern of files?

**Comment by valeriansaliou** [comment]
Hi! If you want to index logs as to perform search in those logs, I'd suggest you build eg. NodeJS log watcher on your end, and use this library to ingest each log line in your Sonic server.
