### ISSUE TITLE
TypeScript definition.

### ISSUE THREAD

**Issue by spacemeowx2** [valeriansaliou/node-sonic-channel#11]
I can make a PR if you don't mind

**Comment by valeriansaliou** [comment]
Hi! What would that be about? I'm not super native w/ TypeScript, can you tell me more? Wouldn't be a better idea to split this in a separate library built in ts?

**Comment by spacemeowx2** [comment]
I'm going to write a TypeScript definition file (https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html). So I can use this library in TS without rewriting.

**Comment by valeriansaliou** [comment]
Got it. Please do, and submit a PR in this repository then. Please also update the README accordingly when you're done.

**Comment by vokilam-d** [comment]
@valeriansaliou Hello!
Can you please publish update to npm with this type definitions?

I'd really appreciate it

**Comment by valeriansaliou** [comment]
@vokilam-d just did, v1.2.6.

**Comment by shajia1992** [comment]
> 如果您不介意我可以做公关

大佬，直播助手对于企鹅平台的订阅失效，求修复
