### ISSUE TITLE
Ingest bulk

### ISSUE THREAD

**Issue by kennetpostigo** [valeriansaliou/node-sonic-channel#14]
I didn't see an example of this, but is it possible to ingest several elements in one push?

**Comment by valeriansaliou** [comment]
Hello there! It's possible to ingest several different text elements referring to the same index object (in a given collection and bucket). To do so, you'd concatenate all text terms to ingest and send them in the same PUSH query to this specific object.

If you want to push different texts on different objects, you'd need to issue separate PUSH queries, as 1 PUSH = 1 object.
