### ISSUE TITLE
Adding support for Promises

### ISSUE THREAD

**Issue by vnglst** [valeriansaliou/node-sonic-channel#3]
Hi Valerian! Thanks for creating and sharing Sonic as an open source db, I've just started experimenting with it and I think it's just what I'm looking for!

I was also looking at your Node.js library and I was wondering if you thought about support for Promises (thus enabling `async/await`)?

I've now added a few helpers to enable that but it would be nice to support it out of the box (or make support easier with [utils.promisfy](https://nodejs.org/dist/latest-v10.x/docs/api/util.html#util_util_promisify_original) by using error first callbacks)

Let me know what you think! (would love to help & contribute PR's)

**Comment by valeriansaliou** [comment]
Hi there!

Thanks for pointing this out. It’s actually planned; no plan to use a library for this, I will implement native promises on my end by wrapping the internal callbacks.

Thanks for the issue, I will use this one to track progress.

**Comment by valeriansaliou** [comment]
FYI, I'm working on it today.

**Comment by valeriansaliou** [comment]
Closed in 8482d703b805295d6f1a3032afd8502cb9c21b70
