### ISSUE TITLE
Better docs for `sonicChannelIngest.push` lang option

### ISSUE THREAD

**Issue by yjh0502** [valeriansaliou/node-sonic-channel#6]
I thought that `{"lang":"US"}` sould be provided for `sonicChannelIngest.push` (based on supported language section of the `sonic` project [1]), but It seems that three-character code from `whatlang` crate should be given for the API [2]. I think it's better to add comment about it.

[1] https://github.com/valeriansaliou/sonic#which-text-languages-are-supported
[2] https://docs.rs/whatlang/0.7.0/whatlang/enum.Lang.html

**Comment by valeriansaliou** [comment]
Hi there! The README specifically refers you to the Sonic Channel specification, which details all argument values. I'd prefer keeping a ground of truth for this on a single page, which is https://github.com/valeriansaliou/sonic/blob/master/PROTOCOL.md
