### ISSUE TITLE
Ingesting with LANG(none)

### ISSUE THREAD

**Issue by danfo** [valeriansaliou/node-sonic-channel#7]
Hi, can we make it possible to ingest with `LANG(none)`? 

https://github.com/valeriansaliou/node-sonic-channel/blob/8482d703b805295d6f1a3032afd8502cb9c21b70/lib/channel/ingest.js#L77

Allowing `{ lang: 'none' }` would be straight-forward, but I guess `{ lang: null }` would also work.

**Comment by valeriansaliou** [comment]
Already works, you'd pass lang=none.

**Comment by valeriansaliou** [comment]
Ah snap, you're right. Fixing this.

**Comment by valeriansaliou** [comment]
All fixed in `v1.2.5`. See: https://www.npmjs.com/package/sonic-channel

Thanks for the report!
